services:
  node:
    build:
      args:
        - NODE_ENV=development
    command: ./node_modules/.bin/nodemon --inspect-brk=0.0.0.0:9229 ./src/app.js
    environment:
      - DEBUG=app:*
    ports:
      - "9229:9229"
    volumes:
      - .:/opt/app
